import spidy.commands.help
import spidy.commands.models
import spidy.commands.connect
import spidy.commands.config_cmd
import spidy.commands.tools
import spidy.commands.skills_cmd
import spidy.commands.memory_cmd
import spidy.commands.sessions_cmd
import spidy.commands.new
import spidy.commands.continue_cmd
import spidy.commands.history
import spidy.commands.review
import spidy.commands.context_cmd
import spidy.commands.doctor_cmd
import spidy.commands.export_cmd
import spidy.commands.share
import spidy.commands.compact
import spidy.commands.update
import spidy.commands.init_cmd
import spidy.commands.agent_cmd
